### ISSUE TITLE
MerkleTree::Node#value fails for nodes in tree which has odd number of txids 

### ISSUE THREAD

**Issue by Yamaguchi** [haw-itn/bitcoinrb#28]
For the tree created by using an odd number of txids,  Node#value failed in this tree.

```
$ ./bin/console 
irb(main):001:0> hashes = ["eabc5a0f2db047073fd8bcc8317b72578f705a0845b33d3c0fa939421219a452", "15157a0138efe2d76ca0ef26f4b42341bd14ff2871603e7364a1d404da51493f"]
=> ["eabc5a0f2db047073fd8bcc8317b72578f705a0845b33d3c0fa939421219a452", "15157a0138efe2d76ca0ef26f4b42341bd14ff2871603e7364a1d404da51493f"]
irb(main):002:0> tree = Bitcoin::MerkleTree.build_partial(3, hashes, Bitcoin.byte_to_bit('1d'.htb))
irb(main):004:0> tree.root.right.value
Traceback (most recent call last):
        5: from ./bin/console:14:in `<main>'
        4: from (irb):4
        3: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:85:in `value'
        2: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:84:in `value'
        1: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:78:in `right='
NoMethodError (undefined method `parent=' for nil:NilClass)
irb(main):005:0> 
```

```
$ bitcoin-cli getblock 58802a21341ec5fc825b68241c1425e82625cbac56a8b18317b27a23101acf00
{
  "hash": "58802a21341ec5fc825b68241c1425e82625cbac56a8b18317b27a23101acf00",
  "confirmations": 1,
  "strippedsize": 435,
  "size": 803,
  "weight": 2108,
  "height": 4031,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "166b3b66ec34f5be025b677961289b0584b6be7a2fb1cc25f4d9e84fd78a2789",
  "tx": [
    "0766fe643cfd100cee17dbd3d035ecac3df10b6fe10d031c718d26d1583ea659",
    "6b049004a60d6e57b507ae8cfbe481aa4c8959c802e724b056a8e29cbf485d9a",
    "3f4951da04d4a164733e607128ff14bd4123b4f426efa06cd7e2ef38017a1515"
  ],
  "time": 1537959102,
  "mediantime": 1537956553,
  "nonce": 0,
  "bits": "207fffff",
  "difficulty": 4.656542373906925e-10,
  "chainwork": "0000000000000000000000000000000000000000000000000000000000001f80",
  "previousblockhash": "566f35243e9e969f6756d78323fa313c3ae3d878242a58ef2ba963d0f5db9221"
}
```

**Comment by Yamaguchi** [comment]
![merkletree](https://user-images.githubusercontent.com/220267/46123702-e505ae00-c25a-11e8-99ee-8d70852d31b4.png)

**Comment by Yamaguchi** [comment]
tree.root.value fails, too.

```
irb(main):019:0> pp tree.root.value
Traceback (most recent call last):
        6: from ./bin/console:14:in `<main>'
        5: from (irb):19
        4: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:85:in `value'
        3: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:85:in `value'
        2: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:84:in `value'
        1: from /Users/h_yamaguchi/Documents/Projects/haw/bitcoinrb/lib/bitcoin/merkle_tree.rb:78:in `right='
NoMethodError (undefined method `parent=' for nil:NilClass)
```
